name: Ensure Code Formatting
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          # install our dependencies
          conda install python=3.7
          conda install -c rdkit rdkit
          conda list
          python -m pip install rdkit-pypi
          python -m pip install networkx==2.1
          python -m pip install pycodestyle autopep8
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install sphinx sphinx-rtd-theme m2r mistune==0.8.4
      
      - name: Check Errors
        run: |
          pycodestyle --statistics --count --max-line-length=150 --show-source .