name: Generate Docs
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          conda install python=3.7
          python -m pip install -e .
          python -m pip install sphinx sphinx-rtd-theme m2r mistune==0.8.4
      
      - name: Generate Documentation
        run: |
          mv docs/index.rst .
          rm docs/*.rst || true
          mv index.rst docs/
          rm README.rst || true
          rm docs/README.rst || true
          rm implemented_metrics.rst || true
          rm docs/implemented_metrics.rst || true
          m2r README.md
          m2r implemented_metrics.md
          mv README.rst docs
          mv implemented_metrics.rst docs
          cd docs
          rm *.html *.doctree
          sphinx-apidoc -f -o . ..
          make clean
          make html
          cp -r _build/html/* .
          cp -r _build/doctrees/* .
          echo "" > .nojekyll
          git add .
          git commit -m "Automated Docs Update" -a || true
          git push -f
