name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          conda install python=3.8
          conda install -c rdkit rdkit
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install coverage
      
      - name: Run Tests
        run: |
          coverage run --source=. --omit=test/* -m unittest discover
      - name: Show Coverage
        run: |
          coverage report -m
